export const productsList = [
    {
      id: "0",
      product: "Delicious pizza with vegetables Super offer off sale for today",
      price: 2.29,
      count: 1,
      countAvailable: "10",
      image: "0.png",
      pineapple: false,
      mushroom: false,
      vegetables: true,
    },
    {
      id: "1",
      product: "Delicious pizza ham mushroom and vegetables off sale for today",
      price: 2.29,
      count: 1,
      countAvailable: "10",
      image: "1.png",
      pineapple: false,
      mushroom: true,
      vegetables: true,
    },
    {
      id: "2",
      product: "Delicious pizza vegetables Super offer off sale for today",
      price: 2.29,
      count: 1,
      countAvailable: "10",
      image: "2.png",
      pineapple: false,
      mushroom: false,
      vegetables: true,
    },
    {
      id: "3",
      product: "Delicious pizza cheese tomato vegetables off sale for today",
      price: 2.29,
      count: 1,
      countAvailable: "10",
      image: "3.png",
      pineapple: false,
      mushroom: false,
      vegetables: true,
    },
    {
      id: "4",
      product: "Delicious pineapple pizza Super offer off sale for today",
      price: 2.29,
      count: 1,
      countAvailable: "10",
      image: "4.png",
      pineapple: true,
      mushroom: false,
      vegetables: true,
    },
    {
      id: "5",
      product: "Delicious pizza vegetables and mushroom off sale for today",
      price: 2.29,
      count: 1,
      countAvailable: "10",
      image: "5.png",
      pineapple: false,
      mushroom: true,
      vegetables: true,
    },
    {
      id: "6",
      product: "Delicious pizza with all Super offer off sale for today",
      price: 2.29,
      count: 1,
      countAvailable: "10",
      image: "6.png",
      pineapple: true,
      mushroom: true,
      vegetables: true,
    },
    {
      id: "7",
      product: "Delicious pizza super vegetable off sale for today",
      price: 2.29,
      count: 1,
      countAvailable: "10",
      image: "7.png",
      pineapple: false,
      mushroom: false,
      vegetables: true,
    },
    {
      id: "8",
      product: "Delicious pizza hottt Super offer off sale for today",
      price: 2.29,
      count: 1,
      countAvailable: "10",
      image: "8.png",
      pineapple: false,
      mushroom: true,
      vegetables: false,
    },
  ];